[package]
name = "nexus"
version = "0.1.0"
edition = "2024"

[lib]
name = "nexus"
crate-type = ["cdylib"]

[dependencies]
indextree = "4.7.4"
logos = "0.15.0"
regex = "1.11.1"

[dependencies.pyo3]
version = "0.24.0"
features = ["abi3-py38"]
